---
- name: Deploy iperf3 Server to Kubernetes
  become: true
  hosts: all
  tasks:
    - include_role:
        name: geerlingguy.docker
      when: kubernetes_role == 'control_plane'
    - name: Copy Directory to Remote Server
      ansible.builtin.copy:
          src: server/
          dest: /tmp/server/
      when: kubernetes_role == 'control_plane'
    - name: Build Docker image
      command: docker build . -t iperf-server
      when: kubernetes_role == 'control_plane'
      args:
        chdir: /tmp/server

    - name: Load Docker image into the Kubernetes nodes (adjust the image name as needed)
      command: docker save -o /tmp/server/iperf-server.tar iperf-server
      when: kubernetes_role == 'control_plane'

    - name: Fetch the file from host1
      ansible.builtin.fetch:
        src: /tmp/server/iperf-server.tar # Adjust the source path on host1
        dest: /tmp/server/iperf-server.tar    # Adjust the destination path on the Ansible controller
        flat: yes
      when: kubernetes_role == 'control_plane'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/server
        state: directory
        mode: '0755'
      when: kubernetes_role == 'node'

    - name: Copy the image tar to worker nodes
      ansible.builtin.copy:
        src: /tmp/server/iperf-server.tar
        dest: /tmp/server/iperf-server.tar
      when: kubernetes_role == 'node'


    - name: Import Containerd image
      command: ctr --address=/var/run/containerd/containerd.sock --namespace=k8s.io image import /tmp/server/iperf-server.tar

    - name: Create Openstack Cloud Provider controller
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'server/manifests/deployment.yml') }}"
      when: kubernetes_role == 'control_plane'
      tags:
        - manifests