---
- hosts: kube1
  become: true

  vars:
    tenants:
      - name: tenant1
        manifest: "manifests/tenant1.yml"
      - name: tenant2
        manifest: "manifests/tenant2.yml"
      - name: tenant3
        manifest: "manifests/tenant3.yml"

  tasks:
    - name: Process each tenant sequentially
      include_tasks: process_tenant.yml
      loop: "{{ tenants }}"
      loop_control:
        loop_var: tenant # Define a custom loop variable to avoid conflicts
