---
- hosts: kube1
  become: true

  tasks:
    - name: Create AMF, NRF deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'manifests/deployment.yml') }}"
        wait: false
    - name: Create AMF, NRF service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'manifests/service.yml') }}"
        wait: true
