sync:
  ingresses:
    enabled: true
  nodes:
    enabled: true
    syncAllNodes: true

mapServices:
  fromVirtual:
    - from: default/upf
      to: upf
    - from: default/amf
      to: amf
  fromHost:
    - from: vcluster-tenant3/smf
      to: default/smf
    - from: vcluster-tenant3/nrf
      to: default/nrf
    - from: vcluster-tenant1/ausf
      to: default/ausf
    - from: vcluster-tenant1/udm
      to: default/udm
    - from: vcluster-tenant3/pcf
      to: default/pcf

isolation:
  enabled: true

  podSecurityStandard: baseline

  resourceQuota:
    enabled: true
    quota:
      requests.cpu: 10
      requests.memory: 20Gi
      requests.storage: "100Gi"
      requests.ephemeral-storage: 60Gi
      limits.cpu: 20
      limits.memory: 40Gi
      limits.ephemeral-storage: 160Gi
      services.nodeports: 0
      services.loadbalancers: 1
      count/endpoints: 40
      count/pods: 20
      count/services: 20
      count/secrets: 100
      count/configmaps: 100
      count/persistentvolumeclaims: 20
    scopeSelector:
      matchExpressions:
    scopes:

  limitRange:
    enabled: true
    default:
      ephemeral-storage: 8Gi
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      ephemeral-storage: 3Gi
      memory: 128Mi
      cpu: 100m

  networkPolicy:
    enabled: true
    outgoingConnections:
      ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 100.64.0.0/10
          - 127.0.0.0/8
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
