kind: Deployment
apiVersion: apps/v1
metadata:
  name: amf-deployment
  namespace: default
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: ghcr.io/henricson/amf:v0.0.26
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nrf-deployment
  namespace: default
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf
          image: ghcr.io/henricson/nrf:v0.0.26
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions
