kind: Deployment
apiVersion: apps/v1
metadata:
  name: amf
  namespace: default
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: ghcr.io/henricson/amf:v0.0.30
          stdin: true
          tty: true
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nrf
  namespace: default
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf
          image: ghcr.io/henricson/nrf:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ausf
  namespace: default
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: ghcr.io/henricson/ausf:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pcf
  namespace: default
  labels:
    app: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
    spec:
      containers:
        - name: pcf
          image: ghcr.io/henricson/pcf:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smf
  namespace: default
  labels:
    app: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: ghcr.io/henricson/smf:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: udm
  namespace: default
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
        - name: udm
          image: ghcr.io/henricson/udm:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: upf
  namespace: default
  labels:
    app: upf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
        - name: upf
          image: ghcr.io/henricson/upf:v0.0.30
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions
