kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnb-deployment
  namespace: default
  labels:
    app: gnb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnb
  template:
    metadata:
      labels:
        app: gnb
    spec:
      containers:
        - name: gnb
          image: ghcr.io/henricson/gnb:v0.0.12
      imagePullSecrets:
        - name: github-actions

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: amf-deployment
  namespace: default
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: gnb

          image: ghcr.io/henricson/amf:v0.0.12
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions
