apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: default
spec:
  selector:
    app: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: default
spec:
  selector:
    app: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
