apiVersion: v1
kind: Service
metadata:
  name: amf-service
  namespace: default
spec:
  selector:
    app: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nrf-service
  namespace: default
spec:
  selector:
    app: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
