---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: udm
  namespace: default
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
        - name: udm
          image: ghcr.io/henricson/udm:v0.0.31
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube-2
---
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: default
spec:
  selector:
    app: udm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ausf
  namespace: default
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: ghcr.io/henricson/ausf:v0.0.31
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-actions
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube-2
---
apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: default
spec:
  selector:
    app: ausf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
