---
swap_file_state: absent

containerd_config_default_write: true
containerd_config_cgroup_driver_systemd: true

kubernetes_config_kubelet_configuration:
  cgroupDriver: systemd

kubernetes_version: 1.29
kubernetes_allow_pods_on_master: true

kubernetes_pod_network:
  # Flannel CNI.
  # cni: 'flannel'
  # cidr: '10.244.0.0/16'
  #
  # Calico CNI.
  cni: "calico"
  cidr: "192.168.0.0/16"
  #
  # Weave CNI.
  # cni: 'weave'
  # cidr: '192.168.0.0/16'
