apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
        - name: iperf-server
          image: iperf-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  namespace: default
spec:
  selector:
    app: iperf-server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
  type: LoadBalancer