apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: default

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: traefik-web-service
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
    loadbalancer.openstack.org/floating-network-id: "730cb16e-a460-4a87-8c73-50a2cb2293f9"

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik