---
- hosts: kube
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Load bridge module
      modprobe:
        name: bridge
        state: present

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.bridge.bridge-nf-call-iptables = 1"
        create: yes

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes

    - name: Apply sysctl parameters from /etc/sysctl.conf
      command: sysctl -p /etc/sysctl.conf

    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache validity in seconds, optional

    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
      tags:
        - manifests

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
      tags:
        - manifests

  roles:
    - geerlingguy.swap
    - geerlingguy.containerd
    - geerlingguy.kubernetes

  tasks:
    - name: Create local-storage StorageClass
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-storage
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer
      tags:
        - manifests
