---
- name: Install vCluster
  become: true
  hosts: kube1

  pre_tasks:
    - name: Download vcluster binary
      ansible.builtin.get_url:
        url: "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64"
        dest: "/tmp/vcluster"
        mode: "0755"

    - name: Install vcluster
      ansible.builtin.copy:
        src: "/tmp/vcluster"
        dest: "/usr/local/bin/vcluster"
        mode: "0755"
        remote_src: yes

    - name: Remove downloaded vcluster binary
      ansible.builtin.file:
        path: "/tmp/vcluster"
        state: absent

  tasks:
    - name: Create multiple vClusters
      ansible.builtin.shell: "vcluster create {{ item }} --connect=false > /tmp/{{ item }}_vcluster_output.log 2>&1"
      loop:
        - tenant1
        - tenant2
        - tenant3
      async: 3600 # Adjust as needed, this is the maximum runtime in seconds
      poll: 0
      register: async_result

    - name: Ensure log files exist for each vCluster
      ansible.builtin.file:
        path: "/tmp/{{ item }}_vcluster_output.log"
        state: touch
      loop:
        - tenant1
        - tenant2
        - tenant3

    - name: Wait for each vCluster to be ready
      ansible.builtin.shell: "grep 'Forwarding from' /tmp/{{ item }}_vcluster_output.log"
      loop:
        - tenant1
        - tenant2
        - tenant3
      register: grep_result
      until: grep_result.rc == 0
      retries: 30 # Number of retries
      delay: 10 # Delay in seconds between retries
      ignore_errors: yes

    - name: Get list of pods in each namespace
      ansible.builtin.command: "kubectl get pods -n {{ item }}"
      loop:
        - tenant1
        - tenant2
        - tenant3
      register: pods_output

    - name: Print the output for each namespace
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ pods_output.results }}"
