name: Build and Push Docker images

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            context: nfs/amf
            image_name: amf
          - dockerfile: Dockerfile
            context: nfs/nrf
            image_name: nrf
          - dockerfile: Dockerfile
            context: nfs/ausf
            image_name: ausf
          - dockerfile: Dockerfile
            context: nfs/pcf
            image_name: pcf
          - dockerfile: Dockerfile
            context: nfs/smf
            image_name: smf
          - dockerfile: Dockerfile
            context: nfs/udm
            image_name: udm
          - dockerfile: Dockerfile
            context: nfs/upf
            image_name: upf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.event.release.tag_name }}
