name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            context: ./benchmarks/vcluster-rtt/amf
            image_name: amf
          - dockerfile: Dockerfile
            context: ./benchmarks/vcluster-rtt/gnb
            image_name: gnb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
